### ISSUE TITLE
Email notifications don't send

### ISSUE THREAD

**Issue by maxnuss** [castle-dev/wall-of-accomplishments#14]
Looks like the last one was on June 20

**Comment by captainsidd** [comment]
@maxnuss This is more likely an issue with the [woa-email-notifications](https://github.com/castle-dev/woa-email-notifications) repo, that actually watches the database and sends the email.

**Comment by maxnuss** [comment]
@sidgonuts didn't know you still read these!

**Comment by lowe0292** [comment]
Looks like the permissions weren't set to public on the woa@ email.
