### ISSUE TITLE
WoA is down!!!!! :( :( :(

### ISSUE THREAD

**Issue by maxnuss** [castle-dev/wall-of-accomplishments#20]

**Comment by lowe0292** [comment]
@maxnuss I feel like we have this conversation once a week.

As usual, not down on my end.

**Comment by maxnuss** [comment]
... the last time you said that you checked again later that day and it _was_ down on your end!

**Comment by lowe0292** [comment]
True, but it was up when I said that, then it came back up on your end without me doing anything!

I blame the internet ghosts 👻
